version: '3.1'
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:example@db/flask'


  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIA_DATABASE: flask

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:5000
